### ISSUE TITLE
Set up Vue

### ISSUE THREAD

**Issue by rjsalvadorr** [rjsalvadorr/rise-of-the-raps#2]
Move the prototype code to a VueJS codebase

**Comment by nickpyren** [comment]
Im still learning about Vue, any specific bootstrapping/libraries you want to use?

**Comment by rjsalvadorr** [comment]
I've got a basic custom flow going on with Vuepress (see https://github.com/rjsalvadorr/rise-of-the-raps/tree/master/docs).

It's finally in place, so you can run it like a typical node project (`npm install` and `npm start`)

**Comment by rjsalvadorr** [comment]
DONE!
